# User Service
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: aze
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Product Service (Change port and DB)
server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: aze

# Order Service
server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: aze
